spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: Password123!
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
